### PR TITLE
Add Turkish translation

### PR DESCRIPTION
**Pull request by Anaxilaus**

### CODE REVIEW

**Comment by hawkeye64** [comment]
@Anaxilaus
Thanks for doing this. Any chance you can fix one line?
```js
rateNormal: 'Normal',
```
Just adjust the 'Normal' to Turkish - thanks.

**Comment by Anaxilaus** [comment]
@hawkeye64 
There's no error, normal is same in Turkish. Etymologically coming from French.

**Comment by hawkeye64** [comment]
@Anaxilaus Well, it got me for sure. :) Will be merging it in before the next release. If you want, you can add yourself to the `Completed Languages` [here](https://github.com/quasarframework/app-extension-qmediaplayer/blob/dev/demo/src/markdown/mediaplayer.md).

**Comment by hawkeye64** [comment]
Thanks again for providing this. You rock! :heart:

**Pull request merged**
